# Generated by Django 2.1 on 2019-05-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0003_auto_20190508_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
