# Generated by Django 2.1 on 2019-05-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0004_auto_20190510_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='christian',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='immember',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
